// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeR8Adwl0pTygwtCfMXha53o16-leNbVM',
    appId: '1:201295479508:web:85dff4d16302158659b141',
    messagingSenderId: '201295479508',
    projectId: 'fir-project-df150',
    authDomain: 'fir-project-df150.firebaseapp.com',
    storageBucket: 'fir-project-df150.appspot.com',
    measurementId: 'G-BZBHHZ3D6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-UWOsPcJPxl-nNTx5SOl_jhI--CKzhaQ',
    appId: '1:201295479508:android:92c17388e854238a59b141',
    messagingSenderId: '201295479508',
    projectId: 'fir-project-df150',
    storageBucket: 'fir-project-df150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9zKp9BrcjzQ-uP0YPceR1BGq2Ohks9I',
    appId: '1:201295479508:ios:5c9506734dd1a35159b141',
    messagingSenderId: '201295479508',
    projectId: 'fir-project-df150',
    storageBucket: 'fir-project-df150.appspot.com',
    iosClientId: '201295479508-bvu7i16p392nj52u314sk832eufibra0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authRouteTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9zKp9BrcjzQ-uP0YPceR1BGq2Ohks9I',
    appId: '1:201295479508:ios:5c9506734dd1a35159b141',
    messagingSenderId: '201295479508',
    projectId: 'fir-project-df150',
    storageBucket: 'fir-project-df150.appspot.com',
    iosClientId: '201295479508-bvu7i16p392nj52u314sk832eufibra0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authRouteTest',
  );
}
